### ISSUE TITLE
Apiman docker init with declarative file launches error

### ISSUE THREAD

**Issue by bilgin1812** [apiman/apiman-cli#38]
Hello,

I created apiman with DockerFile and i execute a script for adding apis, organization and policies.
I used the example[ declarative file](https://github.com/apiman/apiman-cli/blob/master/examples/declarative/common-api-config.yml) in apiman-cli project. But the ones that use Cache Policy do not work.  The "log-headers-policy" of example works but not other. I also replaced the Cache Policy  with Cors Policy and it didn't work either. 
I can see api, organization and gateway created correctly. 

Did you already test these files?
Can any one help me please?

Command for yaml file

`java -jar /opt/apiman-cli/lib/apiman-cli.jar manager apply -f /opt/jboss/wildfly/common-api-config-ORIGINAL.yml --debug`

Logs 

I have "java.lang.Exception: Error: storage transaction is still open for request: /organizations/test/apis/example/versions/1.0/policie" message.

```
{"id":1007,"type":"Api","organizationId":"test","entityId":"example","entityVersion":"1.0","name":"Log Headers Policy","configuration":"{\n  \"direction\" : \"both\"\n}","createdBy":"admin","createdOn":1645431220241,"modifiedBy":"admin","modifiedOn":1645431220241,"definition":{"id":"log-headers-policy","policyImpl":"plugin:io.apiman.plugins:apiman-plugins-log-policy:1.4.3.Final:war/io.apiman.plugins.log_policy.LogHeadersPolicy","name":"Log Headers Policy","description":"A policy that logs the headers to std out.  Useful to analyse inbound HTTP traffic to the gateway when added as the first policy in the chain or to analyse outbound 
HTTP traffic from the gateway when added as the last policy in the chain.","icon":"fire","templates":[],"pluginId":1000,"formType":"JsonSchema","form":"schemas/log-policyDef.schema","deleted":false},"orderIndex":1}    
apiman      | <--- END HTTP (854-byte body)
apiman      | 08:13:40.256 [main] INFO  io.apiman.cli.managerapi.service.PolicyServiceImpl - Adding policy 'CachingPolicy' to API: example
apiman      | ---> HTTP POST http://localhost:8080/apiman/organizations/test/apis/example/versions/1.0/policies
apiman      | Authorization: Basic YWRtaW46YWRtaW4xMjMh
apiman      | Content-Type: application/json; charset=UTF-8
apiman      | Content-Length: 82
apiman      |
apiman      | {
apiman      |   "definitionId" : "CachingPolicy",
apiman      |   "configuration" : "{\n  \"ttl\" : 60\n}"
apiman      | }
apiman      | ---> END HTTP (82-byte body)
apiman      | 08:13:40,332 ERROR [stderr] (default task-1) java.lang.Exception: Error: storage transaction is still open for request: /organizations/test/apis/example/versions/1.0/policies
apiman      | 08:13:40,332 ERROR [stderr] (default task-1)      at deployment.apiman.war//io.apiman.manager.api.war.TransactionWatchdogFilter.doFilter(TransactionWatchdogFilter.java:60)
apiman      | 08:13:40,332 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
apiman      | 08:13:40,333 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
apiman      | 08:13:40,333 ERROR [stderr] (default task-1)      at deployment.apiman.war//io.apiman.common.servlet.DisableCachingFilter.doFilter(DisableCachingFilter.java:52)
apiman      | 08:13:40,333 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
apiman      | 08:13:40,333 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
apiman      | 08:13:40,333 ERROR [stderr] (default task-1)      at deployment.apiman.war//io.apiman.common.servlet.ApimanCorsFilter.doFilter(ApimanCorsFilter.java:88)
apiman      | 08:13:40,333 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
apiman      | 08:13:40,333 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
apiman      | 08:13:40,333 ERROR [stderr] (default task-1)      at deployment.apiman.war//io.apiman.common.servlet.LocaleFilter.doFilter(LocaleFilter.java:61)
apiman      | 08:13:40,334 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
apiman      | 08:13:40,334 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
apiman      | 08:13:40,334 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
apiman      | 08:13:40,334 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)    
apiman      | 08:13:40,334 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
apiman      | 08:13:40,334 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
apiman      | 08:13:40,334 ERROR [stderr] (default task-1)      at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
apiman      | 08:13:40,335 ERROR [stderr] (default task-1)      at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apiman      | 08:13:40,335 ERROR [stderr] (default task-1)      at org.keycloak.keycloak-undertow-adapter@15.1.1//org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
apiman      | 08:13:40,335 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
apiman      | 08:13:40,335 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
apiman      | 08:13:40,335 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
apiman      | 08:13:40,335 ERROR [stderr] (default task-1)      at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
apiman      | 08:13:40,335 ERROR [stderr] (default task-1)      at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apiman      | 08:13:40,336 ERROR [stderr] (default task-1)      at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)     
apiman      | 08:13:40,336 ERROR [stderr] (default task-1)      at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)       
apiman      | 08:13:40,336 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
apiman      | 08:13:40,336 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
apiman      | 08:13:40,336 ERROR [stderr] (default task-1)      at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)     
apiman      | 08:13:40,336 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
apiman      | 08:13:40,336 ERROR [stderr] (default task-1)      at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
apiman      | 08:13:40,337 ERROR [stderr] (default task-1)      at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
apiman      | 08:13:40,337 ERROR [stderr] (default task-1)      at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apiman      | 08:13:40,337 ERROR [stderr] (default task-1)      at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
apiman      | 08:13:40,337 ERROR [stderr] (default task-1)      at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apiman      | 08:13:40,337 ERROR [stderr] (default task-1)      at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
apiman      | 08:13:40,337 ERROR [stderr] (default task-1)      at org.keycloak.keycloak-undertow-adapter@15.1.1//org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
apiman      | 08:13:40,337 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
apiman      | 08:13:40,338 ERROR [stderr] (default task-1)      at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apiman      | 08:13:40,338 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
apiman      | 08:13:40,338 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
apiman      | 08:13:40,338 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
apiman      | 08:13:40,338 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
apiman      | 08:13:40,338 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)apiman      | 08:13:40,338 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
apiman      | 08:13:40,338 ERROR [stderr] (default task-1)      at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
apiman      | 08:13:40,339 ERROR [stderr] (default task-1)      at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
apiman      | 08:13:40,339 ERROR [stderr] (default task-1)      at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
apiman      | 08:13:40,339 ERROR [stderr] (default task-1)      at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
apiman      | 08:13:40,339 ERROR [stderr] (default task-1)      at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
apiman      | 08:13:40,339 ERROR [stderr] (default task-1)      at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)
apiman      | 08:13:40,339 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
apiman      | 08:13:40,339 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
apiman      | 08:13:40,340 ERROR [stderr] (default task-1)      at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
apiman      | 08:13:40,340 ERROR [stderr] (default task-1)      at io.undertow.core@2.2.5.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
apiman      | 08:13:40,340 ERROR [stderr] (default task-1)      at io.undertow.core@2.2.5.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
apiman      | 08:13:40,340 ERROR [stderr] (default task-1)      at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
apiman      | 08:13:40,340 ERROR [stderr] (default task-1)      at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
apiman      | 08:13:40,340 ERROR [stderr] (default task-1)      at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
apiman      | 08:13:40,340 ERROR [stderr] (default task-1)      at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
apiman      | 08:13:40,341 ERROR [stderr] (default task-1)      at org.jboss.xnio@3.8.4.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
apiman      | 08:13:40,341 ERROR [stderr] (default task-1)      at java.base/java.lang.Thread.run(Thread.java:834)
apiman      | 08:13:40,342 ERROR [io.undertow.request] (default task-1) UT005023: Exception handling request to /apiman/organizations/test/apis/example/versions/1.0/policies: javax.servlet.ServletException: java.lang.Exception: Error: storage transaction is still open for request: /organizations/test/apis/example/versions/1.0/policies
apiman      |   at deployment.apiman.war//io.apiman.manager.api.war.TransactionWatchdogFilter.doFilter(TransactionWatchdogFilter.java:64)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
apiman      |   at deployment.apiman.war//io.apiman.common.servlet.DisableCachingFilter.doFilter(DisableCachingFilter.java:52)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
apiman      |   at deployment.apiman.war//io.apiman.common.servlet.ApimanCorsFilter.doFilter(ApimanCorsFilter.java:88)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
apiman      |   at deployment.apiman.war//io.apiman.common.servlet.LocaleFilter.doFilter(LocaleFilter.java:61)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
apiman      |   at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
apiman      |   at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apiman      |   at org.keycloak.keycloak-undertow-adapter@15.1.1//org.keycloak.adapters.undertow.UndertowAuthenticatedActionsHandler.handleRequest(UndertowAuthenticatedActionsHandler.java:66)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:117)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
apiman      |   at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33)
apiman      |   at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apiman      |   at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:53)
apiman      |   at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:59)
apiman      |   at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
apiman      |   at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
apiman      |   at io.undertow.core@2.2.5.Final//io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
apiman      |   at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apiman      |   at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
apiman      |   at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apiman      |   at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
apiman      |   at org.keycloak.keycloak-undertow-adapter@15.1.1//org.keycloak.adapters.undertow.ServletPreAuthActionsHandler.handleRequest(ServletPreAuthActionsHandler.java:69)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
apiman      |   at io.undertow.core@2.2.5.Final//io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
apiman      |   at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
apiman      |   at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)apiman      |   at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)apiman      |   at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)apiman      |   at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)apiman      |   at org.wildfly.extension.undertow@23.0.2.Final//org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1530)apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
apiman      |   at io.undertow.servlet@2.2.5.Final//io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
apiman      |   at io.undertow.core@2.2.5.Final//io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
apiman      |   at io.undertow.core@2.2.5.Final//io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
apiman      |   at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
apiman      |   at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
apiman      |   at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
apiman      |   at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
apiman      |   at org.jboss.xnio@3.8.4.Final//org.xnio.XnioWorker$WorkerThreadFactory$1$1.run(XnioWorker.java:1280)
apiman      |   at java.base/java.lang.Thread.run(Thread.java:834)
apiman      | Caused by: java.lang.Exception: Error: storage transaction is still open for request: /organizations/test/apis/example/versions/1.0/policies
apiman      |   at deployment.apiman.war//io.apiman.manager.api.war.TransactionWatchdogFilter.doFilter(TransactionWatchdogFilter.java:60)
apiman      |   ... 61 more
```

**Comment by msavy** [comment]
Which versions of Apiman are you using?

**Comment by bilgin1812** [comment]
Hello,
Version: | 2.2.1-SNAPSHOT
Built On: | 2022-02-21_10:17

I also tested with 2.1.5.Final but the same result

**Comment by bilgin1812** [comment]
I am trying to set an Apiman server with Docker by using declarative configuration. 
After starting apiman docker 
Docker File
```
FROM apiman/cli:latest as CLI

FROM apiman/on-wildfly
....

```
I apply the configuration and it works except the policy configuration.
``` java -jar /opt/apiman-cli/lib/apiman-cli.jar manager apply -f /opt/jboss/wildfly/common-api-config.yml --debug ```

I don't any error in the logs.
I can see the installed policy in the apiman console but configuration is not applied however i can see my configuration is keeped in parameters.

[![enter image description here][1]][1]

Here is the configuration that i can see when i do F12 on the browser. 

[![enter image description here][2]][2]

My declarative file : common-api-config.yml
```

---
system:
    gateways:
        - name: "gateway"
          description: "Default Gateway"
          type: "REST"
          config:
              endpoint: "http://localhost:8080/apiman-gateway-api"
              username: "apimanager"
              password: "apiman123!"
    plugins:
        - name: "cors-policy"
          groupId: io.apiman.plugins
          artifactId: apiman-plugins-cors-policy
          version: 2.2.3.Final
        - name: "keycloak-oauth-policy"
          groupId: io.apiman.plugins
          artifactId: apiman-plugins-keycloak-oauth-policy
          version: 2.2.3.Final

org:
    name: "org"
    description: "orgproject"
    apis:
        - name: "workflow"
          description: "Service api"
          version: "1.0"
          published: true
          config:
              endpoint: "https://........./"
              endpointType: "rest"
              public: true
              gateway: "gateway"
          policies:
              - name: "cors-policy"
                config:
                    allowOrigin: ["*"]
                    errorOnCorsFailure: true
                    allowCredentials: false
                    exposeHeaders: []
                    allowHeaders: ["Authorization"]
                    allowMethods: ["POST", "GET", "DELETE", "PUT"]
                    maxAge: 0
              - name: "keycloak-oauth-policy"
                config:
                    requireOauth: true
                    requireTransportSecurity: false
                    blacklistUnsafeTokens: false
                    stripTokens: false
                    realm: "https://localhost:8443/auth/realms/apiman"
                    forwardRoles:
                        active: false
                    delegateKerberosTicket: false
                    forwardAuthInfo: []

```


  [1]: https://i.stack.imgur.com/1BVL9.png
  [2]: https://i.stack.imgur.com/0TOlY.png

**Comment by bilgin1812** [comment]
I also tested export/import of configuration with a policy configuration and it doesn't work.
It is really weird, I exported configuration from an working  Apiman instance and imported to an other apiman instance. 
I didn't get any error during the import. Everything is imported except the policy configuration.
Maybe there is a problem with apiman but not apiman-cli?

**Comment by bilgin1812** [comment]
Finally it worked with 2.2.3.Final verison of apiman. 
docker image used is apiman/on-wildfly:2.2.3.Final.

**Comment by msavy** [comment]
@bilgin1812 - any fixes/contributions are welcome, and I am available to provide support to companies.
